name: daily_mistakes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  rflutter_alert: ^1.0.3
  fl_chart: ^0.8.1
  table_calendar: ^2.2.2
  provider: ^3.0.0+1
  date_format: ^1.0.8
  pie_chart: ^3.1.1
  async: ^2.4.0
  sqflite: ^1.2.2+1
  path_provider: ^1.6.5
  path: ^1.6.4
  firebase_messaging: ^6.0.12
  flutter_local_notifications: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: DoHyeon
      fonts:
        - asset: fonts/DoHyeon-Regular.ttf