name: daily_mistakes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  rflutter_alert: ^1.0.3
  fl_chart: ^0.8.1
  table_calendar: ^2.2.2
  provider: ^3.0.0+1
  date_format: ^1.0.8
  pie_chart: ^3.1.1
  async: ^2.4.0
  flutter_local_notifications: ^1.4.0
  shared_preferences: ^0.5.7
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  flutter_spinkit: ^4.1.2+1
  google_sign_in: ^4.4.4
  email_validator: ^1.0.0
  modal_progress_hud: ^0.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_launcher_icons: "^0.7.3"

  # flutter_icons:
  # android: true
  # ios: true
  # image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Title_Light
      fonts:
        - asset: fonts/Title_Light.otf